services:
  - type: web
    name: non-verbal-analysis
    env: python
    buildCommand: chmod +x build_render.sh && ./build_render.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
