services:
  - type: web
    name: non-verbal-analysis
    env: python
    pythonVersion: 3.9.18  # Use a stable Python version for MediaPipe
    buildCommand: bash ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
